version: '3.8'

volumes:
  pgdata:


services:

  db:
    image: postgres:14
    ports:
      - 5432:5432
    networks:
      default:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  default:
    name: sqlalchemy-asyncpg-advisory-lock-int64
